### ISSUE TITLE
POST, PUT and DELETE methods?

### ISSUE THREAD

**Issue by NaelsonDouglas** [EricForgy/Pages.jl#12]
How can I perform posts, puts and deletes?

**Comment by EricForgy** [comment]
Hi @NaelsonDouglas 👋 

If you try:

```julia
> using Pages
> Pages.examples()
```

It will start a server and launch a page in a browser. One of the examples is "Requests". That has an example POST that might be helpful (but until I tag a new version, you'll need to do `Pkg.checkout("Pages")` to get the master branch).

Pages.jl now uses https://github.com/JuliaWeb/HTTP.jl so it might also be helpful to check that out.

I hope this helps 🙏 

PS: My intention with the Request example is to have examples of POST, PUT, DELETE, etc.

**Comment by EricForgy** [comment]
Btw, the example now has `POST` and `GET` with query parameters. I think the other request types are probably clear from this?

https://github.com/EricForgy/Pages.jl/blob/master/examples/requests.jl#L7-L18

**Comment by EricForgy** [comment]
I'll go ahead and close this now. Please reopen or file any new issues if you have any problems 😊
