### ISSUE TITLE
Support routing variables and query parameters

### ISSUE THREAD

**Issue by tk3369** [EricForgy/Pages.jl#13]
I can't find a way to route the call properly when query parameters are provided in the URL e.g. `http://localhost:8888/hello?id=1`.  I expect an `id` parameter should be created in the `Request` object.  Instead, the endpoint for `hello` isn't even called and a `404` error is returned.  It appears that the whole string (`hello?id=1`) becomes the endpoint.

Second, it's common for REST API's to pass arguments as in the path.  For example, the route may be specified as `http://localhost:8888/hello/<city>` and the client calls it as `http://localhost:8888/hello/losangeles`.  In that case, a `city` parameter should be created and accessible to the method.

See Flask examples (http://flask.pocoo.org/docs/0.12/quickstart/#routing)

**Comment by EricForgy** [comment]
Hi @tk3369 👋 

Thanks for pointing that out 👍  This package would not be very useful if it didn't handle query parameters 😅 

Not long ago, I switched this package from HttpServer.jl to HTTP.jl. In the process, I broke the query parameters, but it should be working now.

I expanded the Requests example, so now you can see how to handle both `POST` and `GET` requests with parameters.

https://github.com/EricForgy/Pages.jl/blob/master/examples/requests.jl#L7-L18

To see the example,

```julia
> Pkg.checkout("Pages") # To get the latest master.
> using Pages; Pages.examples() # Wait for a browser window to open, then click "Requests".
```

I hope this helps. Thanks for trying this out and sorry the experience was not great the first time. Let me know if there is anything else I can do.

PS: I will probably not implement routes with variable paths. HTTP.jl has this capability, but I am using my own simple routing. I want to keep this specialized. Of course, you can get the same behavior using query parameters, e.g.

```
http://localhost:8888/hello?city=Los Angeles
```

**Comment by tk3369** [comment]
Hi @EricForgy !  Thanks for the quick response.  I'll try that soon.

**Comment by EricForgy** [comment]
Cool. In that case, I think I will go ahead and close for now. Feel free to reopen or file a new one if you come across anything else 😊

**Comment by tk3369** [comment]
Variable binding is a mandatory requirement to implement any sensible REST API.  See examples in https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api

Is it an issue with your availability?  Perhaps I can help with a PR 😀

**Comment by EricForgy** [comment]
Hi @tk3369 ,

Happy Easter! 😊 

I have a pretty awesome team of developers building best-in-class microservices (not using Pages of course which is my baby and I'm not a developer 😃) and we do not have a single variable endpoint in our entire architecture and I think what we have is sensible 😅 

To allow this would require some special cases in the router and I don't think the difference between

```julia
GET /tickets/12 
```

and

```julia
GET /tickets?id=12 
```

is bad enough to warrant the extra effort in the router 🤔 

It is not difficult. In fact, I had implemented this at one point, but decided to remove it to keep things clean.

If you have a specific use case in mind, I'm happy to work with you to find a suitable workaround, but I prefer not to add variable endpoints to Pages right now 😊

**Comment by EricForgy** [comment]
Actually, come to think of it, you can implement your OWN routing. I will revise Pages to allow this. That is probably best anyway. Thanks for the suggestions! 😊

**Comment by EricForgy** [comment]
We can keep track of it here https://github.com/EricForgy/Pages.jl/issues/14 😊
