### ISSUE TITLE
A small correction

### ISSUE THREAD

**Issue by semmottos** [EricForgy/Pages.jl#16]
This:
     Endpoint("/hello") do request::Request  
should be:
     Endpoint("/hello") do request::HTTP.Request

At least for me it was needed.

And what I get with Pages.pages is really something else than what is shown in the doc.

Jussi Salmela

**Comment by EricForgy** [comment]
Oh man. I don't know how I missed this. Sorry about that. Will have a look.

**Comment by EricForgy** [comment]
I fixed the README. `Pages.pages` doesn't exist anymore because instead of managing routes myself, I rely on HTTP.jl 😊

**Comment by semmottos** [comment]
OK, thanks!
