### ISSUE TITLE
Clean interruption

### ISSUE THREAD

**Issue by tlienart** [EricForgy/Pages.jl#25]
```julia
Pages.examples()
# click blank
Pages.randomping()
```

works fine, however if I interrupt it in the REPL using `CTRL+C` it throws the error and then it seems the server is not closed gracefully (?). 

I think this can be solved by using

```julia
try while true
            sleep(1)
            e = Element(string(count),innerHTML = "Ping $(count): $(round(time()-t0,digits=2)) seconds")
            e.style["color"] = rand(["red","green","blue"])
            rand() < .5 && Pages.appendChild(e)
            count += 1
            tstart = time()
    end
catch err
    if isa(err, InterruptException)
        # close server gracefully
    else
        throw(err)
    end
end
```

The "close server gracefully" part I'm not sure. Maybe one way is to let `Pages.start` take a socket and then close that, something like

```julia
ipaddr = ip"127.0.0.1"
port = 8000
inetaddr = Sockets.InetAddr(ipaddr, port)
server = Sockets.listen(inetaddr)
```

Then in `start` have something like 

```
HTTP.listen(ip"0.0.0.0", p, readtimeout=0, server=server) do http
# ...
```

and finally in the caught interruption above

```
# on interrupt
close(server)
```

?

**Comment by EricForgy** [comment]
Hi @tlienart 👋 

I agree. A clean way to close the example is needed. However, I think control-c _should_ give an error 😅 

I just pushed a new version to `master`. Small change with 

- `appendChild -> append`
- `removeChild -> remove`
- `assign -> update`

There is also a change to `randomping`.

```julia
julia> Pages.examples(launch=true); # <- Decided to make the default NOT launch
```

Then to run the example:

```julia
julia> Pages.randomping.start()
```

To stop:

```julia
julia> Pages.randomping.stop()
```

😊

**Comment by tlienart** [comment]
Great! out of interest why do you think it should Error? it seems that the like of browser-sync (node) and http.server (python) or Hugo etc use it?

Ps: I guess with your PR this can be closed.

**Comment by EricForgy** [comment]
> out of interest why do you think it should Error?

In this case, with this example, control-C, does not feel very elegant 😅 

Having `start` and `stop` methods feels clearner.

For other cases, I can see how control-C would be fine, e.g. it might be nice if control-C would smoothly close down a synchronous / blocking HTTP server.
