### ISSUE TITLE
Is the latest version of this being pulled with: Pkg.add("Pages") ?

### ISSUE THREAD

**Issue by TravisA9** [EricForgy/Pages.jl#4]
Hello, great work on this project. It seems to be just what I need and I hope that I can eventually help supplement this project. Unfortunately, I had to be a bit determined at hacking away at this to get it working as indicated per the readme and eventually came to the realization that what you have here on github is much more complete than what I got on either of my computers (work and home) using `Pkg.add("Pages")`  Is this due to some error on my part or what is going on here?

For some context, I am using julia v0.6.0 on Ubuntu. I was comparing the code on github and realized that the line numbers did not line up with the same code on my computer. I ended up cut-pasting the code and then re-running things after saving and everything works as expected.

**Comment by EricForgy** [comment]
Hi @TravisA9,

I'm guessing you probably figured this out, but I'm guessing that I need to tag a new version. What you see here on Github is the "master" branch. What you get locally when you run 'Pkg.add("Pages")' is the last tagged version. To get "master", try 'Pkg.checkout("Pages")'.

I hope this helps.

**Comment by EricForgy** [comment]
Hi @TravisA9 👋 

I think I will close this issue since it is not specific to this package 😊
