### ISSUE TITLE
how to handle routing without specifying every file?

### ISSUE THREAD

**Issue by TravisA9** [EricForgy/Pages.jl#5]
Sorry if this is a dumb question but I have not been able to get files to the client unless they are specified as per the following:

`Endpoint("/test.js") do request::Request
    readstring(joinpath(dirname(@__FILE__),"test.js"))
end`

What I would like to do is specify the directory and have all of its files available as the client may request them. Is there something I've overlooked because I can't seem to get that working.

**Comment by EricForgy** [comment]
Hi @TravisA9,

Thanks for your question. I haven't implemented anything like a public folder yet, but that should be fairly straightforward to do.

It's been a long time since I worked on this package, but have been looking at it again recently. I'll keep this in mind as a feature request. Feel free to keep this issue opened.

Best regards :)

**Comment by TravisA9** [comment]
Ok, I'm not issuing a pull request for this because I still don't know how/if it could be properly integrated into your project but I have something that could be good as a starting point.

The following code will take a dictionary of "folders" (similar to your pages Dict) and either fetch a default page (index.html) within that directory  ...or any specifically requested page within that directory.


 ```

using HttpServer
import HttpServer.mimetypes

folders = Dict("/MyCoolApp" => 1) 

http = HttpHandler() do req::Request, res::Response

        if haskey(folders, req.resource) # the path is exactly = to a folder so we send the default page.
            Response(readstring(dirname(@__FILE__) * "/index.html"))

        else # the path is somewhere in the/a folder.
            key = match(r"(?:\.(\w+$))", req.resource)[1]  ## uri = URI(req.resource).path
            mime = mimetypes[ key ]
            Response(200, Dict{AbstractString,AbstractString}([("Content-Type",mime)]), readstring(dirname(@__FILE__)*req.resource))
         end
end

server = Server(http)
println("Server listening on 8000...")
run(server,8000)
```

Although this may be close to what is needed, there is a big problem with it. It cannot yet keep track of which directory/endpoint/folder each user is in. That means that it breaks if we try to define more than one folder. The problem is that it needs to associate each user with an endpoint/folder similar to the way websockets does. I really wish I knew enough to be more helpful here.

One option might be to have the folder/endpoint's name included in all requests. So, that means writing:
`<link rel="stylesheet" href="/CodeEditer/css/darkTheme.css" />`
instead of:
`<link rel="stylesheet" href="/css/darkTheme.css" />`
where `"/CodeEditer"` is the endpoint. That's just an idea off the top of my head but you may have a much better solution.

**Comment by TravisA9** [comment]
Ok, I have issued a pull request for a proposed solution. I really hope that this is  reasonable solution but if it's not feel free to reject it or otherwise make modifications as you see fit. If you think this could be a solution then feel free to close this issue.

**Comment by EricForgy** [comment]
Have a look at the latest master: d2848e485031da63fc7bbea3e5ede1035de28f5d

I pushed a version with a new `Public` type that allows you to specify a route and a corresponding path. It currently does not use mimetypes, but I think that should be straightforward to add.

Try

```
julia> using Pages; Pages.Public("/src",joinpath(Pkg.dir("Pages"),"src")); Pages.start()
```

Then navigate to http://localhost:8000/src/Pages.jl.

This seems to do what you want with minimal impact to server.jl.

What do you think?

**Comment by EricForgy** [comment]
Hi @TravisA9 

I decided to stop supporting this feature. I am happy to help you with a work around if you're still interested, but I think I will close this for now 😊
