### ISSUE TITLE
how to get "post" method data in endpoint?

### ISSUE THREAD

**Issue by eseunghwan** [EricForgy/Pages.jl#7]
hello, EricForgy!
I'm testing Pages to replace from python-flask.
In flask, I can recieve requested data both GET and POST.

I wrote code like below,
`using Pages, JSON

Pages.Endpoint("/") do request::Request
    json_out = Dict()
    #param = Pages.query_params(Pages.URI(request.resources))
    #=if request.method == "GET"
        pass
    elseif request.method == "POST"
        pass
    end=#
    #println(fieldnames(request))
    println(request.method)
    println(request.resource)
    println(request.headers)
    println(request.data)
    println(request.uri)

    json_out["a"] = 1

    println(string(json_out))

    return JSON.json(json_out)
end

Pages.Endpoint("/shutdown") do request::Request
    json_out = Dict()

    try
        exit()
        json_out["result"] = "success"
    catch error
        json_out["result"] = string(error)
    end

    return JSON.json(json_out)

end

Pages.start(9000)`

I run very successful, but cannot recieve post datas.

when i post to "/" with python, 
`requests.post("http://localhost:9000", data = json.dumps({"dump": "a"}))`

server prints,
POST
/
Dict{AbstractString,AbstractString}(Pair{AbstractString,AbstractString}("Connection", "keep-alive"),Pair{AbstractString,AbstractString}("http_major", "1"),Pair{AbstractString,AbstractString}("Content-Length", "13"),Pair{AbstractString,AbstractString}("Host", "localhost:9000"),Pair{AbstractString,AbstractString}("Accept", "*/*"),Pair{AbstractString,AbstractString}("http_minor", "1"),Pair{AbstractString,AbstractString}("Keep-Alive", "1"),Pair{AbstractString,AbstractString}("User-Agent", "python-requests/2.18.4"),Pair{AbstractString,AbstractString}("Accept-Encoding", "gzip, deflate"))
UInt8[0x7b, 0x22, 0x64, 0x75, 0x6d, 0x70, 0x22, 0x3a, 0x20, 0x22, 0x61, 0x22, 0x7d]
:/

so there is no data I posted, json.dumps({"dump": "a"})

is there any way to do this?

**Comment by EricForgy** [comment]
Hi @eseunghwan ,

That's awesome! Yes. I am running some APIs using POST. I will "post" some examples :)

Btw, I am in the process of converting Pages from HttpServer to the HTTP and will tag a new version. In the meantime, it might be good to try out master (`Pkg.checkout("Pages")`) 

Btw, I just made the Plotly example more user friendly. You might find it interesting.

On master:

```
> using Pages;
> Pages.examples(); # Note: This will launch a server and open a web page.
```

**Comment by eseunghwan** [comment]
@EricForgy

Thanks for good news!
I'm so excitied about next release :)

Btw, example_plotly show nothing but this.
![image](https://user-images.githubusercontent.com/22045289/35135367-249b8a7c-fd20-11e7-93af-64cd1c448a75.png)

![image](https://user-images.githubusercontent.com/22045289/35135399-6968bab2-fd20-11e7-9056-9ed92b195cc1.png)

Sadly, I'm very noob to julia, I cannot find why it happens

**Comment by EricForgy** [comment]
Hi @eseunghwan 👋 

Try

```
> Pkg.checkout("Pages") # Again, to get on latest master branch.
> Pkg.examples()
```

There is a new example called "Requests". I hope it helps 😊

**Comment by EricForgy** [comment]
Hi @eseunghwan 👋 

I updated the examples so I hope POST requests are clear now 😊
